# Generated by Django 4.2 on 2023-05-02 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
                ('balance_currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euros'), ('JPY', 'Japanese Yen'), ('AUD', 'Australlian Dollar')], default='USD', max_length=3)),
                ('price', models.FloatField()),
                ('price_currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euros'), ('JPY', 'Japanese Yen'), ('AUD', 'Australlian Dollar')], default='USD', max_length=3)),
                ('network', models.CharField(choices=[('MATIC', 'Polygon'), ('ETH', 'Etherium')], default='MATIC', max_length=5)),
                ('address', models.TextField()),
                ('gcard_no', models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(16, 'The field must contain at least 16 characters.')])),
                ('gcard_pin', models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5, 'The field must contain at least 5 characters.')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
