# Generated by Django 4.2 on 2023-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
