# Generated by Django 4.2 on 2023-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_survey_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='validate',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('VAL', 'Validate')], default='DEP', max_length=3),
        ),
    ]
