# Generated by Django 4.2 on 2023-05-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_survey_validate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='validate',
            new_name='method',
        ),
    ]
