# Generated by Django 4.2 on 2023-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_rename_validate_survey_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='store_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
