# Generated by Django 4.2 on 2023-05-03 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_survey_address_alter_survey_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gcard_no',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(16, 'The field must contain at least 16 characters.')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gcard_pin',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5, 'The field must contain at least 5 characters.')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
